receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: "http://jaeger:14250" # Jaeger OTLP gRPC endpoint

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, jaeger]
